### ISSUE TITLE
Deprecated and unrecognized cpp flags

### ISSUE THREAD

**Issue by EnochTheWise** [ivandzen/CubeMX2QBS#1]
qtcreator 4.0.2-1ubuntu2~1
qbs 1.5.2+dfsg-1
gcc-arm-none-eabi 4.9.3+svn231177-1

build:
warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
error: command line option ‘-mthumb’; did you mean ‘-mtbm’?

**Comment by ivandzen** [comment]
It seems that your compiler uses wrong C-frontend. Try to apply the recipe from this post http://stackoverflow.com/questions/8544977/error-while-building-android-ndk-sample-project
